language: python
python:
- '2.7'

branches:
  only:
    - master

env:
  global:
  - GH_REF=github.com/developmentseed/dustduino-server.git
  - secure: J/xHx8h6BVtjtkb/GIu2w0nPQ+2ubqp6CcjywpFHDitjc+Ft2gj31+G4qnUHgNe16q9ssjTF8id5PdMojFBgx6zHaafdSbJ08BpzwwINVKVZWLQy8tnOouiK73bYo+/IttIUmFQ5sguXbRbny1SvSB+Apdp6vkIJydDG/Ay31pA=

install: echo 'no install'

script: echo 'no scripts'

before_install: chmod +x ./.build_scripts/deploy.sh

after_success: ./.build_scripts/deploy.sh
